version: '2'
services:
  nginx:
    container_name: yes.gg
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./:/usr/share/nginx/html
      - ./nginx-dev.conf:/etc/nginx/conf.d/default.conf
