version: '2'
services:
  nginx:
    container_name: yes.gg
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
